"""Word-anchored beat times for web/lie_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'whatever': ('whatever', 1), 'so1': ('so', 1), 'teacher': ('teacher', 1), 'homework': ('homework', 1), 'says': ('says', 1),
    'dragon1': ('dragon', 1), 'ate': ('ate', 1), 'window': ('window', 1), 'explodes': ('explodes', 1), 'dragon2': ('dragon', 2),
    'eats': ('eats', 1), 'homework2': ('homework', 2), 'then1': ('then', 1), 'desk': ('desk', 1),
    'im': ('im', 1), 'fastest': ('fastest', 1), 'now1': ('now', 1), 'ive': ('ive', 1), 'million': ('million', 1),
    'pours': ('pours', 1), 'backpack': ('backpack', 1), 'mia': ('mia', 1), 'cool': ('cool', 1), 'waves': ('waves', 1),
    'then2': ('then', 2), 'crashes': ('crashes', 1), 'bike1': ('bike', 1), 'tree': ('tree', 1),
    'did1': ('did', 1), 'break': ('break', 1), 'panics': ('panics', 1), 'dude': ('dude', 1), 'never': ('never', 1), 'before': ('before', 1),
    'stops': ('stops', 1), 'stares': ('stares', 1), 'stranger': ('stranger', 1), 'because': ('because', 1), 'one1': ('one', 1),
    'sorry': ('sorry', 1), 'who1': ('who', 1), 'lies2': ('lies', 2), 'youre1': ('youre', 1), 'best': ('best', 1), 'friend': ('friend', 1),
    'wasnt': ('wasnt', 1), 'now3': ('now', 3), 'grins': ('grins', 1), 'hugs': ('hugs', 1),
    'then3': ('then', 3), 'sees': ('sees', 1), 'bro': ('bro', 1), 'broke': ('broke', 1),
    'almost': ('almost', 1), 'dragon3': ('dragon', 3), 'something': ('something', 1), 'lands': ('lands', 1), 'roof': ('roof', 1),
    'shuts': ('shuts', 1), 'first': ('first', 1), 'truth': ('truth', 1), 'iDid': ('did', 2),
    'then4': ('then', 4), 'buying': ('buying', 1), 'newOne': ('one', 2), 'fine': ('fine', 1), 'million2': ('million', 2), 'dollars2': ('dollars', 2),
    'two': ('two', 1), 'record': ('record', 1), 'follow': ('follow', 1), 'school': ('school', 1), 'she': ('she', 1), 'dollars1': ('dollars', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
