"""Word-anchored beat times for web/google_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'one1': ('one', 1), 'guy': ('guy', 1), 'types': ('types', 1), 'gcom': ('googlecom', 1), 'shop': ('shop', 1), 'says': ('says', 1),
    'available': ('available', 1), 'twelve1': ('twelve', 1), 'clicks': ('clicks', 1), 'buy': ('buy', 1), 'goes': ('goes', 1),
    'minute': ('minute', 1), 'owns': ('owns', 1), 'visited': ('visited', 1), 'earth': ('earth', 1), 'inbox': ('inbox', 1),
    'messages': ('messages', 1), 'run': ('run', 1), 'owner': ('owner', 1), 'laptop': ('laptop', 1), 'then': ('then', 1),
    'cancelled': ('cancelled', 1), 'twelve2': ('twelve', 2), 'refunded': ('refunded', 1), 'wants': ('wants', 1), 'back': ('back', 1),
    'reports': ('reports', 1), 'security': ('security', 1), 'send': ('send', 1), 'reward': ('reward', 1), 'six1': ('six', 1),
    'thirteen': ('thirteen', 1), 'write': ('write', 1), 'squint': ('squint', 1),
    'd1': ('six', 3), 'd2': ('zero', 1), 'd3': ('zero', 2), 'd4': ('six', 4), 'd5': ('one', 3), 'd6': ('three', 1),   # 'six' 1-2 and 'one' 1-2 come earlier in the script
    'l1': ('g', 1), 'l2': ('o', 1), 'l3': ('o', 2), 'l4': ('g', 2), 'l5': ('l', 1), 'l6': ('e', 1),
    'doesnt': ('doesnt', 1), 'asks': ('asks', 1), 'charity': ('charity', 1), 'schools': ('schools', 1), 'india': ('india', 1),
    'doubles': ('doubles', 1), 'over': ('over', 1), 'twelve3': ('twelve', 3), 'twelve4': ('twelve', 4), 'website4': ('website', 4),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
