"""Word-anchored beat times for web/nose_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'some': ('some', 1), 'fingerprints': ('fingerprints', 1), 'this': ('this', 1), 'super': ('super', 1), 'gamepass': ('gamepass', 1),
    'smell': ('smell', 1), 'anything': ('anything', 1), 'map': ('map', 1), 'case1': ('case', 1), 'stole': ('stole', 1),
    'golden1': ('golden', 1), 'donut1': ('donut', 1), 'chief1': ('chief', 1), 'wanted': ('wanted', 1), 'tonight': ('tonight', 1),
    'scene': ('scene', 1), 'girl': ('girl', 1), 'single': ('single', 1), 'tempting1': ('tempting', 1), 'case2': ('case', 2),
    'only': ('only', 1), 'clue': ('clue', 1), 'sock1': ('sock', 1), 'cheap': ('cheap', 1), 'cologne': ('cologne', 1), 'bad': ('bad', 1),
    'decisions': ('decisions', 1), 'hint': ('hint', 1), 'tuesday': ('tuesday', 1), 'night': ('night', 1), 'trail1': ('trail', 1),
    'pool1': ('pool', 1), 'party': ('party', 1), 'mia': ('mia', 1), 'liked': ('liked', 1), 'nose2': ('nose', 2), 'asked': ('asked', 1),
    'stay': ('stay', 1), 'tempting2': ('tempting', 2), 'case3': ('case', 3), 'ended': ('ended', 1), 'guy1': ('guy', 1),
    'sunglasses': ('sunglasses', 1), 'threw': ('threw', 1), 'pepper': ('pepper', 1), 'big': ('big', 1), 'mistake': ('mistake', 1),
    'achoo': ('achoo', 1), 'into': ('into', 1), 'pool2': ('pool', 2), 'both': ('both', 1), 'socks': ('socks', 1), 'guy2': ('guy', 2),
    'trail2': ('trail', 2), 'back': ('back', 2), 'chiefs': ('chiefs', 1), 'office': ('office', 1), 'one2': ('one', 2), 'sock2': ('sock', 2),
    'sprinkles': ('sprinkles', 1), 'face': ('face', 1), 'half': ('half', 1), 'donut2': ('donut', 2), 'said': ('said', 1),
    'going': ('going', 1), 'away': ('away', 1), 'slid': ('slid', 1), 'cut': ('cut', 1), 'tempting3': ('tempting', 3),
    'took': ('took', 1), 'bite': ('bite', 1), 'read': ('read', 1), 'rights': ('rights', 1), 'you': ('you', 1),
    'remain': ('remain', 1), 'sprinkled': ('sprinkled', 1), 'closed': ('closed', 1),
    'twitched': ('twitched', 1), 'follow': ('follow', 1), 'next': ('next', 1),
}
NUM = {'1': 'one', '2': 'two'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45 if line.strip() else 0.5
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
