"""Max's lip-sync track from the narration: one mouth shape per frame (30 fps) -> web/lipsync.js.

    python3 source/lipsync.py       # after fix_captions.py (uses audio/alignment/captions.json + audio/narration.wav)

Each word's measured time is split over its letter groups (vowel groups weigh more than consonant groups) and mapped to the
pack's lip-sync mouths: c = mouth_closed (m, b, p), s = mouth_small (most consonants), w = mouth_wide (a, i), o = mouth_o
(o, u, w), e = mouth_e (e, ee, y). Frames where the voice is quiet close the mouth ('n' = flat neutral line inside a phrase,
'-' = rest: the expression's own mouth). Single-frame shapes are merged into their neighbours so nothing flickers.
"""
import json, re, wave
import numpy as np
from pathlib import Path
P = Path(__file__).resolve().parent.parent
FPS = 30

with wave.open(str(P / 'audio/narration.wav')) as w:
    sr, n, ch = w.getframerate(), w.getnframes(), w.getnchannels()
    x = np.frombuffer(w.readframes(n), dtype=np.int16).astype(np.float32).reshape(-1, ch).mean(1) / 32768
hop = sr // FPS
rms = np.array([np.sqrt(np.mean(x[i * hop:(i + 1) * hop] ** 2) + 1e-12) for i in range(len(x) // hop + 1)])
loud = rms > max(0.012, np.percentile(rms, 60) * 0.18)

words = [(w['word'].strip(), w['start'], w['end']) for c in json.loads((P / 'audio/alignment/captions.json').read_text()) for w in c['words']]
frames = len(rms) + FPS
track = ['-'] * frames


def shape(group):
    g = group.lower()
    if re.fullmatch(r'[aeiouy]+', g):
        if 'o' in g or 'u' in g: return 'o'
        if g in ('e', 'ee', 'ea', 'ei', 'ey', 'y', 'ie'): return 'e'
        return 'w'
    if re.search(r'[mbp]', g): return 'c'
    if re.search(r'w|wh|qu', g): return 'o'
    return 's'


for text, a, b in words:
    letters = re.sub(r"[^a-zA-Z]", '', text) or 'a'
    if len(letters) > 2 and re.search(r'[^aeiouy]e$', letters.lower()): letters = letters[:-1]       # silent final e (some, use, nose)
    groups = re.findall(r'[aeiouyAEIOUY]+|[^aeiouyAEIOUY]+', letters)
    weights = [1.6 if re.fullmatch(r'[aeiouyAEIOUY]+', g) else 1.0 for g in groups]
    tot, t = sum(weights), a
    for g, wgt in zip(groups, weights):
        d = (b - a) * wgt / tot
        for f in range(int(round(t * FPS)), int(round((t + d) * FPS))):
            if 0 <= f < frames: track[f] = shape(g)
        t += d
    # a short gap to the next word inside a phrase is a flat closed mouth, not a rest
for (_, _, b), (_, a2, _) in zip(words, words[1:]):
    if a2 - b < 0.35:
        for f in range(int(round(b * FPS)), int(round(a2 * FPS))):
            if track[f] == '-': track[f] = 'n'
# quiet frames inside words close the mouth
for f in range(min(frames, len(loud))):
    if track[f] in 'swoe' and not loud[f]: track[f] = 'n'
# no single-frame shapes
for f in range(1, frames - 1):
    if track[f] != track[f - 1] and track[f] != track[f + 1]: track[f] = track[f - 1]
s = ''.join(track).rstrip('-')
(P / 'web/lipsync.js').write_text('// Generated by source/lipsync.py - do not edit by hand. One mouth per frame at 30 fps:\n'
                                  '// c closed, s small, w wide, o round, e smile-teeth, n flat (pause in a phrase), - rest (expression mouth).\n'
                                  f'export const LIPS = {json.dumps(s)};\n')
print('lipsync', len(s), 'frames;', {k: s.count(k) for k in 'cswoen-'})
