"""Word-anchored beat times for web/emperor_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'fiftynine': ('fiftynine', 1), 'broke': ('broke', 1), 'francisco': ('francisco', 1), 'declares': ('declares', 1), 'emperor1': ('emperor', 1),
    'states1': ('states', 1), 'city1': ('city', 1), 'along': ('along', 1), 'name': ('name', 1), 'norton1': ('norton', 1),
    'rich': ('rich', 1), 'buy': ('buy', 1), 'rice1': ('rice', 1), 'town': ('town', 1),
    'ship1': ('ship', 1), 'ship2': ('ship', 2), 'rice2': ('rice', 2), 'arrived': ('arrived', 1), 'lost': ('lost', 1), 'everything': ('everything', 1),
    'writes': ('writes', 1), 'newspaper': ('newspaper', 1), 'norton2': ('norton', 2), 'first': ('first', 1), 'emperor2': ('emperor', 2), 'states2': ('states', 2),
    'paper': ('paper', 1), 'prints1': ('prints', 1),
    'wears': ('wears', 1), 'uniform': ('uniform', 1), 'gold': ('gold', 1), 'epaulettes': ('epaulettes', 1), 'feathered': ('feathered', 1), 'hat': ('hat', 1),
    'prints2': ('prints', 2), 'money': ('money', 1), 'shops': ('shops', 1), 'accept': ('accept', 1),
    'orders1': ('orders', 1), 'congress1': ('congress', 1), 'shut': ('shut', 1), 'congress2': ('congress', 2), 'ignores': ('ignores', 1),
    'police': ('police', 1), 'officer': ('officer', 1), 'arrests': ('arrests', 1), 'city2': ('city', 2), 'furious': ('furious', 1),
    'chief': ('chief', 1), 'go': ('go', 1), 'officers': ('officers', 1), 'salute': ('salute', 1), 'street': ('street', 1),
    'orders2': ('orders', 2), 'bridge': ('bridge', 1), 'bay': ('bay', 1), 'decades': ('decades', 1), 'built2': ('built', 2),
    'dies': ('dies', 1), 'thousands': ('thousands', 1), 'streets': ('streets', 1), 'goodbye': ('goodbye', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    ALIAS = {'1859': 'fiftynine'}         # numerals Whisper writes for spoken words
    heard = [(ALIAS.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
