"""Word-anchored beat times for web/noob_clip.js.

  python3 source/beats.py            # from audio/alignment/captions.json (real narration) if present,
                                     # else an estimate from script.txt at Part 3's measured pace
Writes web/beats.js (export const W = {name: seconds}) so the clip retimes itself when the narration lands.
Anchors are (word, occurrence) pairs, matched in order on lower-cased words with punctuation stripped.
"""
import json, re
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'moved': ('moved', 1), 'leoLaughed': ('laughed', 1), 'kick': ('kick', 1), 'typedFaster': ('faster', 1), 'fling': ('fling', 1),
    'gone': ('gone', 1), 'maxTried': ('tried', 1), 'giant': ('giant', 1), 'tiny': ('tiny', 1), 'shrank': ('shrank', 1),
    'invisible': ('invisible', 1), 'hair': ('hair', 1), 'fire': ('fire', 1), 'ran': ('ran', 1), 'screaming': ('screaming', 1),
    'freeze': ('freeze', 1), 'spin': ('spin', 1), 'sit': ('sit', 1), 'dance': ('dance', 1), 'fourCmds': ('four', 1),
    'charged': ('charged', 1), 'speed': ('speed', 1), 'intoEach': ('each', 1), 'other': ('other', 1), 'andMia': ('mia', 1),
    'hadnt': ('hadnt', 1), 'wholeRound': ('round', 2), 'ten': ('ten', 1), 'walked': ('walked', 1), 'poked': ('poked', 1),
    'fell': ('fell', 1), 'plank': ('plank', 1), 'gg': ('gg', 1), 'popped': ('popped', 1), 'miasName': ('name', 1),
    'alt': ('alt', 1), 'wholeTime': ('time', 2), 'partThree': ('three', 1), 'didnt': ('didnt', 1), 'forget': ('forget', 1),
    'follow': ('follow', 1), 'end': (None, 0),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())

def words():
    cap = P / 'audio/alignment/captions.json'
    if cap.is_file():
        return [(w['word'], w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words']], 'narration'
    out, t = [], 0.0                               # estimate: Part 3 pace (0.33 s/word, 0.42 s per line break, +0.4 for "...")
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.split():
            out.append((w, t, t + 0.28)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.42
    return out, 'estimate'

ws, src = words()
B, seen = {}, {}
for name, (word, occ) in ANCHORS.items():
    if word is None: B[name] = round(ws[-1][2], 2); continue
    n = 0
    for w, s, e in ws:
        if norm(w) == word:
            n += 1
            if n == occ: B[name] = round(s, 2); break
    else: raise SystemExit(f'anchor not found: {name} ({word} #{occ})')
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(B, indent=1)};\n')
print(src, 'speech ends', B['end'], '->', len(B), 'anchors')
