"""Word-anchored beat times for web/barrel_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'schoolteacher': ('schoolteacher', 1), 'climbs1': ('climbs', 1), 'barrel1': ('barrel', 1), 'niagara': ('niagara', 1), 'falls1': ('falls', 1),
    'nobody': ('nobody', 1), 'ever': ('ever', 1), 'survived1': ('survived', 1),
    'its': ('its', 1), 'birthday': ('birthday', 1),
    'tells': ('tells', 1), 'twenty1': ('twenty', 1), 'younger': ('younger', 1),
    'shes2': ('shes', 2), 'broke': ('broke', 1), 'thinks': ('thinks', 1), 'rich': ('rich', 1),
    'two': ('two', 1), 'cat1': ('cat', 1), 'first': ('first', 1), 'test': ('test', 1),
    'cat2': ('cat', 2), 'survived2': ('survived', 2),
    'so': ('so', 1), 'friends': ('friends', 1), 'pump1': ('pump', 1), 'bicycle': ('bicycle', 1),
    'they': ('they', 1), 'seal': ('seal', 1), 'lid': ('lid', 1), 'adrift': ('adrift', 1), 'river': ('river', 1),
    'current': ('current', 1), 'rushes': ('rushes', 1), 'edge': ('edge', 1),
    'over3': ('over', 3), 'goes': ('goes', 1), 'horseshoe': ('horseshoe', 1), 'falls2': ('falls', 2),
    'about': ('about', 1), 'minutes': ('minutes', 1), 'rescuers': ('rescuers', 1), 'grab': ('grab', 1),
    'climbs2': ('climbs', 2), 'cut': ('cut', 1), 'head': ('head', 1), 'alive': ('alive', 1),
    'verdict': ('verdict', 1), 'never': ('never', 1), 'again': ('again', 1),
    'shes3': ('shes', 3), 'famous': ('famous', 1), 'money': ('money', 1), 'pouring': ('pouring', 1),
    'then': ('then', 1), 'manager': ('manager', 1), 'runs': ('runs', 1), 'barrel5': ('barrel', 5),
    'spends': ('spends', 1), 'savings': ('savings', 1), 'detectives': ('detectives', 1), 'back': ('back', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
