"""Word-anchored beat times for web/paperclip_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'posts': ('posts', 1), 'clip1': ('paperclip', 1), 'online': ('online', 1), 'offers': ('offers', 1), 'bigger': ('bigger', 1),
    'plan': ('plan', 1), 'trading': ('trading', 1), 'owns': ('owns', 1), 'house1': ('house', 1),
    'someone': ('someone', 1), 'swaps': ('swaps', 1), 'pen1': ('pen', 1), 'fish': ('fish', 1),
    'same': ('same', 1), 'pen2': ('pen', 2), 'knob1': ('doorknob', 1), 'face': ('face', 1),
    'knob2': ('doorknob', 2), 'camping': ('camping', 1), 'stove1': ('stove', 1),
    'stove2': ('stove', 2), 'generator': ('generator', 1),
    'tbt': ('trade', 2), 'snowmobile': ('snowmobile', 1), 'trip': ('trip', 1), 'truck': ('truck', 1), 'record': ('record', 1),
    'rent': ('rent', 1), 'free': ('free', 1),
    'then': ('then', 1), 'worst': ('worst', 1), 'afternoon': ('afternoon', 1), 'rock': ('rock', 1), 'star': ('star', 1),
    'globe1': ('globe', 1), 'people': ('people', 1), 'dumbest': ('dumbest', 1), 'made': ('made', 1),
    'but': ('but', 1), 'actor': ('actor', 1), 'six': ('six', 1), 'globes': ('globes', 1),
    'wants1': ('wants', 1), 'this1': ('this', 1), 'so': ('so', 1), 'part1': ('part', 1), 'movie2': ('movie', 2),
    'tiny': ('tiny', 1), 'canada': ('canada', 1), 'wants2': ('wants', 2), 'part2': ('part', 2),
    'auditions': ('auditions', 1), 'pay': ('pay', 1), 'house2': ('house', 2),
    'oneyear': ('year', 2), 'fourteen': ('fourteen', 1), 'trades': ('trades', 1),
    'clip2': ('paperclip', 2), 'became': ('became', 1), 'house3': ('house', 3),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
