"""Word-anchored beat times for web/clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'job': ('job', 1), 'guard': ('guard', 1), 'steals': ('steals', 1), 'chase': ('chase', 1), 'jungle': ('jungle', 1),
    'safe': ('safe', 1), 'bonk': ('bonk', 1), 'cross': ('cross', 1), 'nobody': ('nobody', 1), 'month': ('month', 1),
    'four': ('four', 1), 'boss': ('boss', 1), 'star': ('star', 1), 'disguise': ('disguise', 1), 'sunglasses': ('sunglasses', 1),
    'hoodie': ('hoodie', 1), 'tag': ('tag', 1), 'player2': ('player', 2), 'read': ('read', 1), 'through': ('through', 1),
    'behind': ('behind', 1), 'bases': ('bases', 1), 'full': ('full', 1), 'leos': ('leos', 1), 'most': ('most', 1), 'took': ('took', 1),
    'chased': ('chased', 1), 'stop': ('stop', 1), 'home': ('home', 1), 'sat': ('sat', 1), 'stars': ('stars', 1), 'hatched': ('hatched', 1),
    'once': ('once', 1), 'baby': ('baby', 1), 'jobs': ('jobs', 1), 'quit': ('quit', 1), 'hired': ('hired', 1), 'snacks': ('snacks', 1),
    'treadmill': ('treadmill', 1), 'brainrot': ('brainrot', 1), 'best': ('best', 1), 'kids': ('kids', 1), 'follow': ('follow', 1),
}
NUM = {'400': 'four', '1': 'one', '5': 'five'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
