"""Word-anchored beat times for web/clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'bigger': ('bigger', 1), 'plan': ('plan', 1), 'skip': ('skip', 1), 'jumped': ('jumped', 1), 'fifty': ('fifty', 1),
    'stepped': ('stepped', 1), 'lava': ('lava', 1), 'tried': ('tried', 1), 'tinyBlock': ('tiny', 1), 'block': ('block', 1),
    'grew': ('grew', 1), 'didnt': ('didnt', 1), 'back': ('back', 1), 'checkpoint': ('checkpoint', 1), 'start': ('start', 1),
    'reached': ('reached', 1), 'steps': ('steps', 1), 'door': ('door', 1), 'tinyDoor': ('tiny', 2), 'trophy': ('trophy', 1),
    'fit': ('fit', 1), 'shrink': ('shrink', 1), 'reset': ('reset', 1), 'sat': ('sat', 1), 'nobody': ('nobody', 1),
    'typed': ('typed', 1), 'hundred': ('hundred', 1), 'say': ('say', 1), 'ninety': ('ninety', 1), 'cracked': ('cracked', 1),
    'oneHundred': ('hundred', 2), 'fell': ('fell', 1), 'map': ('map', 1), 'clear': ('clear', 1), 'giant': ('giant', 1),
    'stomped': ('stomped', 1), 'respawned': ('respawned', 1), 'lastCp': ('checkpoint', 2), 'next': ('next', 1),
    'tinyAgain': ('tiny', 3), 'shrunk': ('shrunk', 1), 'free': ('free', 1), 'walked': ('walked', 1), 'grabbed': ('grabbed', 1),
    'victory': ('victory', 1), 'vjump': ('jump', 2), 'small': ('small', 1), 'room': ('room', 1), 'nextGame': ('next', 2),
    'faster': ('faster', 1), 'follow': ('follow', 1),
}
NUM = {'99': 'ninetynine', '100': 'hundred', '50': 'fifty'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
