"""Word-anchored beat times for web/clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'twice': ('twice', 1), 'alt': ('alt', 1), 'teamed': ('teamed', 1), 'fling': ('fling', 1), 'flying': ('flying', 1),
    'noticed': ('noticed', 1), 'froze': ('froze', 1), 'poked': ('poked', 1), 'plank': ('plank', 1), 'onlyPlay': ('play', 1),
    'attacked': ('attacked', 1), 'maxFor': ('went', 2), 'leoFor': ('went', 3), 'sw1': ('switched', 1), 'sw2': ('switched', 2),
    'sw3': ('switched', 3), 'faster': ('faster', 1), 'freeze': ('freeze', 1), 'justFreeze': ('freeze', 2), 'wrong': ('wrong', 1),
    'herself': ('herself', 1), 'ten': ('ten', 1), 'save': ('save', 1), 'meant': ('meant', 1), 'typo': ('typed', 3),
    'newCrowns': ('crowns', 1), 'lasted': ('lasted', 1), 'kickMax': ('typed', 4), 'kickLeo': ('typed', 5), 'enter': ('enter', 1),
    'same': ('same', 1), 'kicked': ('kicked', 1), 'roundOver': ('round', 2), 'wins': ('wins', 1), 'again': ('again', 1),
    'chat': ('chat', 1), 'skye': ('skye', 1), 'joined': ('joined', 1), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
