"""Word-anchored beat times for web/emu_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'twenty': ('twenty', 1), 'emus1': ('emus', 1), 'farms': ('farms', 1), 'eating': ('eating', 1), 'wheat': ('wheat', 1),
    'farmers': ('farmers', 1), 'soldiers': ('soldiers', 1), 'ask': ('ask', 1), 'help': ('help', 1),
    'sends': ('sends', 1), 'major1': ('major', 1), 'gunners': ('gunners', 1), 'machine1': ('machine', 1), 'ten': ('ten', 1), 'bullets1': ('bullets', 1),
    'day1': ('day', 1), 'coming': ('coming', 1), 'split': ('split', 1), 'tiny': ('tiny', 1), 'run': ('run', 1),
    'day3': ('day', 2), 'thousand1': ('thousand', 3), 'ambush': ('ambush', 1), 'jams': ('jams', 1),
    'bolts': ('bolts', 1), 'truck1': ('truck', 1), 'outrun': ('outrun', 1), 'ride': ('ride', 1), 'bumpy': ('bumpy', 1), 'aim': ('aim', 1),
    'every': ('every', 1), 'lookout': ('lookout', 1), 'tall': ('tall', 1), 'watch': ('watch', 1), 'eat': ('eat', 1),
    'after': ('after', 1), 'week': ('week', 1), 'half': ('half', 1), 'gone': ('gone', 1), 'most': ('most', 1), 'arent': ('arent', 1),
    'parliament': ('parliament', 1), 'laugh': ('laugh', 1), 'medals': ('medals', 1), 'pulls': ('pulls', 1),
    'admits': ('admits', 1), 'birds': ('birds', 1), 'tanks': ('tanks', 1),
    'went': ('went', 1), 'war': ('war', 1), 'won': ('won', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
