"""Word-anchored beat times for web/palace_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'postman': ('postman', 1), 'trips': ('trips', 1), 'stone1': ('stone', 1), 'almost': ('almost', 1), 'falls': ('falls', 1),
    'kick': ('kick', 1), 'away': ('away', 1), 'puts': ('puts', 1), 'pocket': ('pocket', 1),
    'strange': ('strange', 1), 'stone2': ('stone', 2), 'reminds': ('reminds', 1), 'dream': ('dream', 1), 'palace1': ('palace', 1),
    'so1': ('so', 1), 'mail': ('mail', 1), 'round': ('round', 1), 'starts': ('starts', 1), 'picking': ('picking', 1), 'stones': ('stones', 1),
    'first': ('first', 1), 'pockets': ('pockets', 1), 'baskets': ('baskets', 1), 'brings': ('brings', 1), 'wheelbarrow': ('wheelbarrow', 1),
    'night': ('night', 1), 'oil': ('oil', 1), 'lamp': ('lamp', 1), 'builds1': ('builds', 1),
    'whole': ('whole', 1), 'village1': ('village', 1), 'laughs': ('laughs', 1),
    'keeps': ('keeps', 1), 'twenty': ('twenty', 1), 'outer': ('outer', 1), 'walls': ('walls', 1),
    'animals': ('animals', 1), 'giants': ('giants', 1), 'towers': ('towers', 1),
    'later': ('later', 1), 'finished': ('finished', 1), 'ten': ('ten', 1), 'days': ('days', 1), 'hours': ('hours', 1),
    'writes': ('writes', 1), 'let': ('let', 1), 'better': ('better', 1), 'try': ('try', 1),
    'asks': ('asks', 1), 'buried': ('buried', 1), 'law': ('law', 1), 'no': ('no', 1),
    'so2': ('so', 2), 'builds2': ('builds', 2), 'tomb': ('tomb', 1), 'eight': ('eight', 1), 'more': ('more', 1),
    'today': ('today', 1), 'protected': ('protected', 1), 'monument': ('monument', 1),
    'village2': ('village', 2), 'laughed': ('laughed', 1), 'famous': ('famous', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
