"""Word-anchored beat times for web/tornado_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'tornado1': ('tornado', 1), 'wrecks': ('wrecks', 1), 'fifty': ('fifty', 1), 'planes1': ('planes', 1), 'base1': ('base', 1),
    'five1': ('five', 1), 'days': ('days', 1), 'later': ('later', 1), 'two': ('two', 1), 'weathermen': ('weathermen', 1), 'say1': ('say', 1),
    'coming': ('coming', 1), 'back': ('back', 1),
    'tornadoes1': ('tornadoes', 1), 'called': ('called', 1), 'impossible': ('impossible', 1), 'predict': ('predict', 1),
    'weather1': ('weather', 1), 'service': ('service', 1), 'allowed': ('allowed', 1), 'use': ('use', 1), 'word': ('word', 1),
    'but': ('but', 1), 'general1': ('general', 1), 'furious': ('furious', 1),
    'if': ('if', 1), 'forecast1': ('forecast', 1), 'rain': ('rain', 1), 'why': ('why', 1), 'tornadoes2': ('tornadoes', 2),
    'so': ('so', 1), 'dig': ('dig', 1), 'old': ('old', 1), 'records': ('records', 1),
    'on': ('on', 1), 'day5': ('five', 2), 'map': ('map', 1), 'exactly': ('exactly', 1), 'night': ('night', 1), 'hit': ('hit', 1),
    'odds': ('odds', 1), 'another1': ('another', 1), 'hitting': ('hitting', 1), 'same1': ('same', 1), 'base2': ('base', 2),
    'billions': ('billions', 1), 'one2': ('one', 2),
    'general2': ('general', 2), 'stares': ('stares', 1), 'radar': ('radar', 1),
    'another2': ('another', 2), 'tornado3': ('tornado', 3), 'yes1': ('yes', 1), 'no': ('no', 1),
    'they2': ('they', 2), 'say2': ('say', 2), 'yes2': ('yes', 2),
    'planes2': ('planes', 2), 'roll': ('roll', 1), 'hangars': ('hangars', 1),
    'everyone': ('everyone', 1), 'heads': ('heads', 1), 'shelter': ('shelter', 1),
    'one3': ('one', 3), 'weatherman': ('weatherman', 1), 'goes': ('goes', 1), 'home': ('home', 1), 'wondering': ('wondering', 1),
    'job': ('job', 1), 'running': ('running', 1), 'elevator': ('elevator', 1),
    'at': ('at', 3), 'six': ('six', 1), 'oclock': ('oclock', 1), 'tornado4': ('tornado', 4), 'hits': ('hits', 1), 'base3': ('base', 3), 'again': ('again', 1),
    'almost': ('almost', 1), 'same2': ('same', 2), 'spot': ('spot', 1),
    'this': ('this', 1), 'time': ('time', 1), 'ready': ('ready', 1),
    'first': ('first', 1), 'official': ('official', 1), 'tornado5': ('tornado', 5), 'forecast2': ('forecast', 2), 'ever': ('ever', 1), 'true': ('true', 1),
    'and': ('and', 1), 'warnings': ('warnings', 1), 'born': ('born', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
