"""Word-anchored beat times for web/mona_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'smock': ('smock', 1), 'lifts': ('lifts', 1), 'wall1': ('wall', 1), 'nobody': ('nobody', 1), 'used': ('used', 1),
    'staircase': ('staircase', 1), 'dumps': ('dumps', 1), 'glass': ('glass', 1), 'locked': ('locked', 1), 'door': ('door', 1),
    'plumber': ('plumber', 1), 'opens': ('opens', 1),
    'morning': ('morning', 1), 'artist': ('artist', 1), 'paint': ('paint', 1), 'four': ('four', 1), 'hooks': ('hooks', 1),
    'guards': ('guards', 1), 'shrug': ('shrug', 1), 'photographed': ('photographed', 1), 'isnt': ('isnt', 1),
    'museum1': ('museum', 1), 'shuts': ('shuts', 1), 'week': ('week', 1), 'sixty': ('sixty', 1), 'police1': ('police', 1), 'search': ('search', 1),
    'question': ('question', 1), 'picasso': ('picasso', 1),
    'detective': ('detective', 1), 'visits': ('visits', 1), 'room': ('room', 1), 'report': ('report', 1), 'leaning': ('leaning', 1),
    'table': ('table', 1), 'hidden': ('hidden', 1),
    'reopens': ('reopens', 1), 'crowds': ('crowds', 1), 'queue': ('queue', 1), 'stare': ('stare', 1), 'empty': ('empty', 1), 'wall2': ('wall', 2),
    'face': ('face', 1), 'newspapers': ('newspapers', 1), 'everywhere': ('everywhere', 1),
    'two': ('two', 1), 'later': ('later', 1), 'sell': ('sell', 1), 'italy': ('italy', 1),
    'dealer': ('dealer', 1), 'checks': ('checks', 1), 'real': ('real', 1), 'calls': ('calls', 1), 'police2': ('police', 2),
    'stole': ('stole', 1), 'hardly': ('hardly', 1), 'talked': ('talked', 1),
    'handed': ('handed', 1), 'famous': ('famous', 1), 'world': ('world', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
