"""Word-anchored beat times for web/umbrella_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'umbrella1': ('umbrella', 1), 'dry1': ('dry', 1), 'everyone1': ('everyone', 1), 'soaked1': ('soaked', 1), 'sky': ('sky', 1),
    'blue': ('blue', 1), 'opens1': ('opens', 1), 'storm': ('storm', 1), 'over': ('over', 1), 'except': ('except', 1),
    'max1': ('max', 1), 'soaked2': ('soaked', 2), 'mia1': ('mia', 1), 'soaked3': ('soaked', 3), 'passing': ('passing', 1),
    'dog': ('dog', 1), 'soaked4': ('soaked', 4), 'closes': ('closes', 1), 'sun': ('sun', 1), 'back': ('back', 1),
    'sharing': ('sharing', 1), 'max2': ('max', 2), 'squeeze': ('squeeze', 1), 'dry2': ('dry', 2), 'noob1': ('noob', 1),
    'fit': ('fit', 1), 'noob2': ('noob', 2), 'thunderstorm': ('thunderstorm', 1), 'after': ('after', 1), 'closed': ('closed', 1),
    'then': ('then', 1), 'barbecue': ('barbecue', 1), 'flips': ('flips', 1), 'grill1': ('grill', 1), 'volcano': ('volcano', 1),
    'flames': ('flames', 1), 'table': ('table', 1), 'napkins': ('napkins', 1), 'bouncy': ('bouncy', 1), 'screams': ('screams', 1),
    'opens2': ('opens', 2), 'umbrella2': ('umbrella', 2), 'rain': ('rain', 1), 'hammers': ('hammers', 1), 'grill2': ('grill', 2),
    'hisses': ('hisses', 1), 'gone': ('gone', 1), 'thirty': ('thirty', 1), 'cheer': ('cheer', 1), 'dry3': ('dry', 3), 'boy': ('boy', 1),
    'mia2': ('mia', 2), 'ducks': ('ducks', 1), 'room': ('room', 1), 'more': ('more', 1), 'moves': ('moves', 1),
    'everyone4': ('everyone', 4), 'wet': ('wet', 1), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
