"""Word-anchored beat times for web/race_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'book1': ('book', 1), 'world1': ('world', 1), 'eighty': ('eighty', 1), 'days1': ('days', 1),
    'reporter': ('reporter', 1), 'faster': ('faster', 1), 'editor': ('editor', 1), 'job': ('job', 1), 'man1': ('man', 1),
    'start': ('start', 1), 'man2': ('man', 2), 'beat1': ('beat', 1),
    'two1': ('two', 1), 'sails': ('sails', 1), 'dress': ('dress', 1), 'coat': ('coat', 1), 'bag': ('bag', 1),
    'france': ('france', 1), 'meet': ('meet', 1), 'wrote': ('wrote', 1), 'book2': ('book', 2),
    'suez': ('suez', 1), 'ceylon': ('ceylon', 1), 'singapore': ('singapore', 1),
    'hong': ('hong', 1), 'news': ('news', 1), 'magazine': ('magazine', 1), 'rival1': ('rival', 1), 'other': ('other', 1),
    'same': ('same', 1), 'papers': ('papers', 1), 'race': ('race', 1),
    'storms': ('storms', 1), 'pacific': ('pacific', 1), 'cost': ('cost', 1), 'two2': ('two', 2),
    'newspaper': ('newspaper', 1), 'special': ('special', 1), 'train': ('train', 1), 'races': ('races', 1), 'america': ('america', 1),
    'seventytwo': ('seventytwo', 1), 'six': ('six', 1), 'hours': ('hours', 1), 'eleven': ('eleven', 1), 'minutes': ('minutes', 1),
    'beat2': ('beat', 2), 'book3': ('book', 3), 'eight': ('eight', 1),
    'rival2': ('rival', 2), 'home': ('home', 1), 'four': ('four', 1), 'half': ('half', 1), 'later': ('later', 2),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    NUM = {'80': 'eighty', '72': 'seventytwo', '6': 'six', '11': 'eleven'}      # the transcriber writes these as digits
    heard = [(NUM.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
