"""Word-anchored beat times for web/penguin_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'penguin1': ('penguin', 1), 'inspects': ('inspects', 1), 'soldiers1': ('soldiers', 1), 'salute1': ('salute', 1), 'outranks': ('outranks', 1),
    'started': ('started', 1), 'seventytwo': ('seventytwo', 1), 'norways': ('norways', 1), 'guard1': ('guard', 1), 'zoo1': ('zoo', 1),
    'scotland': ('scotland', 1), 'adopts': ('adopts', 1), 'name1': ('name', 1), 'nils': ('nils', 1), 'lance': ('lance', 1), 'corporal1': ('corporal', 1),
    'every': ('every', 2), 'back': ('back', 1), 'promoted': ('promoted', 1), 'corporal2': ('corporal', 2), 'sergeant1': ('sergeant', 1),
    'regimental': ('regimental', 1), 'major1': ('major', 1),
    'penguins': ('penguins', 1), 'change': ('change', 1), 'dies': ('dies', 1), 'lookalike': ('lookalike', 1), 'rank': ('rank', 1),
    'king': ('king', 1), 'knight': ('knight', 1), 'hundred': ('hundred', 1), 'march': ('march', 1), 'ceremony': ('ceremony', 1),
    'citation': ('citation', 1), 'qualified': ('qualified', 1),
    'bronze': ('bronze', 1), 'statue': ('statue', 1), 'brigadier': ('brigadier', 1), 'twentythree': ('twentythree', 1), 'major2': ('major', 2), 'general': ('general', 1),
    'trained': ('trained', 1), 'salute2': ('salute', 2), 'waddles': ('waddles', 1), 'past': ('past', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    ALIAS = {'1972': 'seventytwo', '130': 'hundred', '2023': 'twentythree'}         # numerals Whisper writes for spoken words
    heard = [(ALIAS.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
