"""Word-anchored beat times for web/crown_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'copies': ('copies', 1), 'crown1': ('crown', 1), 'step1': ('step', 1), 'jump1': ('jump', 1), 'whoever2': ('whoever', 2),
    'timer': ('timer', 1), 'million': ('million', 1), 'coins': ('coins', 1),
    'leo1': ('leo', 1), 'grabs': ('grabs', 1), 'three1': ('three', 1), 'forward': ('forward', 1),
    'so1': ('so', 1), 'max2': ('max', 2), 'standing': ('standing', 1), 'edge': ('edge', 1), 'lava': ('lava', 1), 'splash1': ('splash', 1),
    'respawns': ('respawns', 1), 'charges': ('charges', 1), 'touch': ('touch', 1), 'yours': ('yours', 1),
    'leo2': ('leo', 2), 'backwards1': ('backwards', 1), 'max4': ('max', 4), 'never': ('never', 1), 'closer': ('closer', 1),
    'shows': ('shows', 1), 'spins1': ('spins', 1), 'server': ('server', 1), 'spins2': ('spins', 2),
    'dances1': ('dances', 1), 'everyone2': ('everyone', 2), 'dances2': ('dances', 2),
    'ten': ('ten', 1), 'stops': ('stops', 1), 'soak': ('soak', 1),
    'mia1': ('mia', 1), 'walks2': ('walks', 2), 'smiling': ('smiling', 1),
    'leo5': ('leo', 5), 'amazing': ('amazing', 1), 'take': ('take', 1), 'bow1': ('bow', 1),
    'resist': ('resist', 1), 'bows': ('bows', 1), 'so3': ('so', 4), 'mia2': ('mia', 2),
    'bonk': ('bonk', 1), 'hits': ('hits', 1), 'hers': ('hers', 1),
    'three2': ('three', 2), 'mia3': ('mia', 3), 'step2': ('step', 2), 'back': ('back', 1),
    'so4': ('so', 5), 'everyone3': ('everyone', 3), 'leo6': ('leo', 6), 'backwards2': ('backwards', 2), 'game2': ('game', 2),
    'splash2': ('splash', 2), 'splash3': ('splash', 3), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
