"""Word-anchored beat times for web/mia_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'anything': ('anything', 1), 'life': ('life', 1), 'still': ('still', 1), 'wheels': ('wheels', 1), 'very': ('very', 1), 'exactly': ('exactly', 1), 'cant': ('cant', 1), 'dog': ('dog', 1), 'fetches': ('fetches', 1),
    'bike': ('bike', 1), 'square': ('square', 1), 'bonk1': ('bonk', 1), 'bonk2': ('bonk', 2), 'boyfriend': ('boyfriend', 1),
    'supportive': ('supportive', 1), 'then': ('then', 1), 'leo': ('leo', 1), 'grabs1': ('grabs', 1), 'pencil2': ('pencil', 2),
    'watch': ('watch', 1), 'learn': ('learn', 1), 'draws1': ('draws', 1), 'lion1': ('lion', 1), 'every1': ('every', 1),
    'hair': ('hair', 1), 'every2': ('every', 2), 'tooth': ('tooth', 1), 'perfect': ('perfect', 1), 'roars': ('roars', 1),
    'screams': ('screams', 1), 'lion2': ('lion', 2), 'corners': ('corners', 1), 'leo2': ('leo', 2),
    'mia3': ('mia', 3), 'grabs2': ('grabs', 2), 'draws2': ('draws', 2), 'cage': ('cage', 1), 'bars': ('bars', 1),
    'wobbly': ('wobbly', 1), 'hold': ('hold', 1), 'forgot': ('forgot', 1), 'roof': ('roof', 1), 'lion3': ('lion', 3),
    'jumps': ('jumps', 1), 'out': ('out', 1), 'stick2': ('stick', 2), 'boyfriend2': ('boyfriend', 2), 'steps': ('steps', 1),
    'bats': ('bats', 1), 'toy': ('toy', 1), 'stops': ('stops', 1), 'just': ('just', 1), 'cat': ('cat', 1),
    'one': ('one', 1), 'anyone': ('anyone', 1), 'scribbles': ('scribbles', 1), 'ball': ('ball', 1), 'yarn': ('yarn', 1),
    'lion4': ('lion', 4), 'pounces': ('pounces', 1), 'purrs': ('purrs', 1), 'once': ('once', 1), 'perfectly': ('perfectly', 1),
    'wants': ('wants', 1), 'another': ('another', 1), 'no': ('no', 1), 'good': ('good', 1), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
