"""Word-anchored beat times for web/banana_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'pays': ('pays', 1), 'six1': ('six', 1), 'banana1': ('banana', 1), 'then1': ('then', 1), 'eats1': ('eats', 1),
    'started': ('started', 1), 'miami': ('miami', 1), 'artist1': ('artist', 1), 'banana2': ('banana', 2), 'calls': ('calls', 1), 'art2': ('art', 2),
    'collectors': ('collectors', 1), 'hundred': ('hundred', 1), 'each': ('each', 1),
    'days': ('days', 1), 'peels': ('peels', 1), 'eats2': ('eats', 2), 'gallery': ('gallery', 1), 'panic': ('panic', 1),
    'tape': ('tape', 1), 'new': ('new', 1), 'because': ('because', 1), 'never': ('never', 1), 'certificate': ('certificate', 1),
    'instructions': ('instructions', 1), 'brown': ('brown', 1), 'replace': ('replace', 1),
    'years': ('years', 1), 'seoul': ('seoul', 1), 'student': ('student', 1), 'eats3': ('eats', 3), 'skipped': ('skipped', 1), 'breakfast': ('breakfast', 1),
    'then2': ('then', 2), 'auction': ('auction', 1), 'york': ('york', 1), 'bids': ('bids', 1), 'million2': ('million', 2),
    'three': ('three', 1), 'five': ('five', 1), 'six2': ('six', 2), 'dollars3': ('dollars', 3),
    'buyer': ('buyer', 1), 'stage': ('stage', 1), 'itself': ('itself', 1), 'street': ('street', 1), 'stand': ('stand', 1),
    'sold': ('sold', 1), 'cents': ('cents', 1), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    ALIAS = {}         # numerals Whisper writes for spoken words
    heard = [(ALIAS.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
