"""Word-anchored beat times for web/marathon_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'first1': ('first', 1), 'olympic': ('olympic', 1), 'line1': ('line', 1), 'rode': ('rode', 1), 'eleven': ('eleven', 1), 'car1': ('car', 1),
    'and1': ('and', 1), 'nearly': ('nearly', 1), 'gold': ('gold', 1), 'medal1': ('medal', 1),
    'st': ('st', 1), 'louis': ('louis', 1), 'over': ('over', 1), 'ninety': ('ninety', 1), 'degrees': ('degrees', 1),
    'cars': ('cars', 1), 'kick': ('kick', 1), 'dust': ('dust', 1), 'faces': ('faces', 1),
    'theres': ('theres', 1), 'one1': ('one', 1), 'water': ('water', 1), 'whole': ('whole', 1), 'race': ('race', 1),
    'at1': ('at', 1), 'mile1': ('mile', 1), 'nine': ('nine', 1), 'quits': ('quits', 1), 'climbs': ('climbs', 1), 'car2': ('car', 2),
    'behind': ('behind', 1), 'cuban': ('cuban', 1), 'mailman1': ('mailman', 1), 'street': ('street', 1), 'cut': ('cut', 1), 'knee': ('knee', 1),
    'stops': ('stops', 1), 'chat': ('chat', 1), 'crowd1': ('crowd', 1),
    'eats': ('eats', 1), 'apples': ('apples', 1), 'orchard': ('orchard', 1),
    'rotten': ('rotten', 1), 'so1': ('so', 1), 'lies': ('lies', 1), 'nap': ('nap', 1),
    'another': ('another', 1), 'chased': ('chased', 1), 'mile2': ('mile', 2), 'course': ('course', 1), 'dog': ('dog', 1),
    'then': ('then', 1), 'breaks': ('breaks', 1), 'mile3': ('mile', 3), 'nineteen2': ('nineteen', 2),
    'so2': ('so', 2), 'passenger': ('passenger', 1), 'jogs': ('jogs', 1), 'rest': ('rest', 1),
    'crosses': ('crosses', 1), 'line2': ('line', 2), 'first2': ('first', 2), 'crowd2': ('crowd', 2), 'roars': ('roars', 1),
    'about': ('about', 1), 'medal2': ('medal', 2), 'until': ('until', 1), 'officials': ('officials', 1), 'hear': ('hear', 1), 'car4': ('car', 4),
    'banned': ('banned', 1),
    'and3': ('and', 3), 'napped': ('napped', 1), 'still': ('still', 1), 'fourth': ('fourth', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
