"""Word-anchored beat times for web/dog_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'town': ('town', 1), 'time1': ('time', 1), 'kids': ('kids', 1), 'sick': ('sick', 1), 'medicine1': ('medicine', 1),
    'seven': ('seven', 1), 'away': ('away', 1), 'ships': ('ships', 1), 'ice1': ('ice', 1), 'planes': ('planes', 1),
    'cold': ('cold', 1), 'dogs': ('dogs', 1), 'twenty': ('twenty', 1), 'relay': ('relay', 1), 'one': ('one', 1),
    'hardest': ('hardest', 1), 'leader': ('leader', 1), 'twelve': ('twelveyearold', 1), 'togo1': ('togo', 1),
    'run': ('run', 1), 'seventy': ('seventy', 1), 'reach': ('reach', 1), 'turn': ('turn', 1), 'back': ('back', 1),
    'togo2': ('togo', 2), 'shortcut': ('shortcut', 1), 'frozen': ('frozen', 1), 'blizzard': ('blizzard', 1),
    'night': ('night', 1), 'storm': ('storm', 1), 'ice2': ('ice', 2), 'sea2': ('sea', 2), 'crossed': ('crossed', 1),
    'time2': ('time', 2), 'two': ('two', 1), 'sixtyone': ('sixtyone', 1), 'more': ('more', 1), 'five': ('five', 1),
    'arrives': ('arrives', 1), 'outbreak': ('outbreak', 1), 'stopped': ('stopped', 1), 'but': ('but', 1),
    'ran': ('ran', 1), 'fiftythree': ('fiftythree', 1), 'statue': ('statue', 1), 'york': ('york', 1),
    'balto': ('balto', 1), 'togo3': ('togo', 3), 'wait': ('wait', 1), 'seventysix': ('seventysix', 1),
    'years': ('years', 1), 'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    NUM = {'20': 'twenty', '12yearold': 'twelveyearold', '170': 'seventy', '261': 'sixtyone', '53': 'fiftythree', '76': 'seventysix'}      # the transcriber writes these as digits
    heard = [(NUM.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
