"""Word-anchored beat times for web/mail_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'climbs': ('climbs', 1), 'crate': ('crate', 1), 'friend1': ('friend', 1), 'nails': ('nails', 1), 'shut': ('shut', 1),
    'inside': ('inside', 1), 'pillow': ('pillow', 1), 'torch': ('torch', 1), 'tinned': ('tinned', 1), 'bottles': ('bottles', 1),
    'water': ('water', 1), 'later1': ('later', 1),
    'athlete': ('athlete', 1), 'broke': ('broke', 1), 'london': ('london', 1), 'daughters': ('daughters', 1), 'birthday1': ('birthday', 1),
    'australia1': ('australia', 1), 'mailing': ('mailing', 1), 'home': ('home', 1),
    'label': ('label', 1), 'paint': ('paint', 1), 'cash': ('cash', 1), 'delivery': ('delivery', 1), 'company': ('company', 1), 'exist': ('exist', 1),
    'fog': ('fog', 1), 'grounds': ('grounds', 1), 'hours1': ('hours', 1),
    'bombay': ('bombay', 1), 'upside': ('upside', 1), 'tarmac': ('tarmac', 1), 'burning': ('burning', 1), 'sun': ('sun', 1),
    'sixty': ('sixtythree', 1), 'later2': ('later', 2), 'lands': ('lands', 1), 'perth': ('perth', 1),
    'cuts': ('cuts', 1), 'puts': ('puts', 1), 'suit': ('suit', 1), 'walks': ('walks', 1), 'airport': ('airport', 1),
    'hitchhikes': ('hitchhikes', 1), 'australia2': ('australia', 2),
    'makes': ('makes', 1), 'birthday2': ('birthday', 2),
    'forgets': ('forgets', 1), 'telling': ('telling', 1), 'friend2': ('friend', 2), 'survived': ('survived', 1),
    'friend3': ('friend', 3), 'panics': ('panics', 1), 'calls': ('calls', 1), 'newspaper': ('newspaper', 1),
    'whole': ('whole', 1), 'world': ('world', 1), 'knows': ('knows', 1),
    'airline': ('airline', 1), 'drops': ('drops', 1), 'bill': ('bill', 1),
    'afford': ('afford', 1), 'ticket': ('ticket', 1), 'theend': ('end', 1), 'never': ('never', 1), 'paid': ('paid', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
