"""Word-anchored beat times for web/wrongway_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'takes': ('takes', 1), 'heading': ('heading', 1), 'california1': ('california', 1),
    'twentyeight': ('twentyeight', 1), 'lands1': ('lands', 1), 'ireland': ('ireland', 1),
    'for': ('for', 2), 'years': ('years', 1), 'asked': ('asked', 1), 'atlantic': ('atlantic', 1),
    'officials1': ('officials', 1), 'no1': ('no', 1), 'his1': ('his', 1), 'plane': ('plane', 1), 'old': ('old', 1), 'patched': ('patched', 1),
    'so': ('so', 1), 'filed': ('filed', 1), 'flight': ('flight', 1), 'california2': ('california', 2),
    'at': ('at', 1), 'dawn': ('dawn', 1), 'took': ('took', 1), 'kept': ('kept', 1), 'east': ('east', 1), 'into1': ('into', 1), 'clouds1': ('clouds', 1),
    'no2': ('no', 2), 'radio': ('radio', 1), 'twenty': ('twentyyearold', 1), 'compass1': ('compass', 1),
    'then': ('then', 1), 'fuel': ('fuel', 1), 'leaked': ('leaked', 1), 'cockpit': ('cockpit', 1),
    'punched': ('punched', 1), 'hole': ('hole', 1), 'floor': ('floor', 1), 'screwdriver': ('screwdriver', 1), 'drain': ('drain', 1),
    'lands2': ('lands', 2), 'dublin': ('dublin', 1), 'climbs': ('climbs', 1), 'says': ('says', 1),
    'just': ('just', 1), 'where': ('where', 1), 'am': ('am', 1),
    'excuse': ('excuse', 1), 'clouds2': ('clouds', 2), 'misread': ('misread', 1), 'compass2': ('compass', 2),
    'officials2': ('officials', 2), 'sent': ('sent', 1), 'telegram': ('telegram', 1), 'rules': ('rules', 1), 'broke': ('broke', 1),
    'punishment': ('punishment', 1), 'flying2': ('flying', 2), 'until': ('until', 1), 'ship': ('ship', 1), 'home': ('home', 1),
    'new3': ('new', 3), 'threw': ('threw', 1), 'parade': ('parade', 1), 'bigger': ('bigger', 1), 'lindberghs': ('lindberghs', 1),
    'they': ('they', 1), 'called': ('called', 1), 'wrong': ('wrong', 1), 'corrigan': ('corrigan', 1),
    'and4': ('and', 4), 'never': ('never', 1), 'admitted': ('admitted', 1), 'thing': ('thing', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
