"""Word-anchored beat times for web/tower_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'say': ('say', 1), 'name1': ('name', 1), 'teleport': ('teleport', 1), 'next1': ('next', 1),
    'first': ('first', 1), 'tower': ('tower', 1), 'wins': ('wins', 1), 'million1': ('million', 1), 'coins1': ('coins', 1),
    'leo1': ('leo', 1), 'jump1': ('jump', 1), 'top2': ('top', 2),
    'max1': ('max', 1), 'bottom1': ('bottom', 1), 'leo2': ('leo', 2), 'pop1': ('pop', 1), 'leos': ('leos', 1), 'back': ('back', 1), 'bottom2': ('bottom', 2),
    'max2': ('max', 2), 'climbs': ('climbs', 1), 'yells': ('yells', 1), 'max3': ('max', 3), 'pop2': ('pop', 2),
    'up1': ('up', 1), 'leo4': ('leo', 4), 'down1': ('down', 1), 'up2': ('up', 2), 'max4': ('max', 4), 'down2': ('down', 2),
    'so': ('so', 1), 'changes': ('changes', 1), 'tag1': ('tag', 1), 'steve1': ('steve', 1),
    'leo6': ('leo', 6), 'nothing': ('nothing', 1), 'climbing': ('climbing', 1),
    'max5': ('max', 5), 'squints': ('squints', 1), 'tag2': ('tag', 2), 'steve2': ('steve', 2), 'pop3': ('pop', 3),
    'mia1': ('mia', 1), 'ledge': ('ledge', 1), 'lava1': ('lava', 1),
    'turns': ('turns', 1), 'sweetly': ('sweetly', 1), 'max6': ('max', 6), 'leo7': ('leo', 7),
    'pop4': ('pop', 4), 'pop5': ('pop', 5), 'appear': ('appear', 1), 'midair': ('in', 2),
    'straight': ('straight', 1), 'lava2': ('lava', 2),
    'now': ('now', 1), 'mia2': ('mia', 2), 'noob1': ('noob', 1), 'three': ('three', 1), 'top3': ('top', 3),
    'easy': ('easy', 1), 'reads': ('reads', 1), 'tag3': ('tag', 3),
    'x1': ('x', 1), 'underscore1': ('underscore', 1), 'dark': ('dark', 1), 'shadow': ('shadow', 1), 'dragon': ('dragon', 1),
    'slayer': ('slayer', 1), 'underscore2': ('underscore', 2), 'x3': ('x', 3), 'two': ('two', 1), 'thousand': ('thousand', 1), 'and2': ('and', 2),
    'noob2': ('noob', 2), 'jumps': ('jumps', 1), 'nine': ('nine', 1),
    'pop6': ('pop', 6), 'appears': ('appears', 1), 'holding': ('holding', 1), 'million2': ('million', 2), 'coins2': ('coins', 2),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
