"""Word-anchored beat times for web/chair_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'man1': ('man', 1), 'sits1': ('sits', 1), 'chair1': ('chair', 1), 'tied': ('tied', 1), 'fortytwo': ('fortytwo', 1), 'balloons1': ('balloons', 1),
    'plan': ('plan', 1), 'hundred': ('hundred', 1), 'feet1': ('feet', 1), 'held': ('held', 1), 'rope1': ('rope', 1),
    'rope2': ('rope', 2), 'snaps': ('snaps', 1),
    'thousand1': ('thousand', 1), 'five': ('five', 1), 'sixteen': ('sixteen', 1), 'thousand3': ('thousand', 3),
    'its': ('its', 1), 'freezing': ('freezing', 1),
    'hed': ('hed', 1), 'fly': ('fly', 1), 'eyesight': ('eyesight', 1), 'enough': ('enough', 1),
    'packed': ('packed', 1), 'sandwiches': ('sandwiches', 1), 'pellet': ('pellet', 1), 'gun1': ('gun', 1), 'pop': ('pop', 1), 'balloons2': ('balloons', 2),
    'two': ('two', 1), 'airline': ('airline', 1), 'pilots': ('pilots', 1), 'radio': ('radio', 1), 'tower1': ('tower', 1),
    'passed': ('passed', 1), 'man2': ('man', 2), 'chair2': ('chair', 2),
    'pops': ('pops', 1), 'few': ('few', 1), 'starts': ('starts', 1), 'sink': ('sink', 1),
    'then': ('then', 1), 'drops': ('drops', 1), 'gun2': ('gun', 2),
    'drifts': ('drifts', 1), 'power': ('power', 1), 'lines': ('lines', 1), 'whole': ('whole', 1), 'dark': ('dark', 1),
    'lands': ('lands', 1), 'unhurt': ('unhurt', 1), 'police': ('police', 1), 'waiting': ('waiting', 1),
    'reporters': ('reporters', 1), 'why': ('why', 1),
    'man3': ('man', 3), 'cant': ('cant', 1), 'sit': ('sit', 1), 'around': ('around', 1),
    'fined': ('fined', 1), 'flying': ('flying', 1), 'aircraft1': ('aircraft', 1), 'calling': ('calling', 1), 'tower2': ('tower', 2),
    'aircraft2': ('aircraft', 2), 'lawn3': ('lawn', 3), 'chair3': ('chair', 3),
    'never': ('never', 1), 'allowed': ('allowed', 1), 'pilot': ('pilot', 1),
    'today': ('today', 1), 'chair4': ('chair', 4), 'sits2': ('sits', 2), 'air': ('air', 1), 'space': ('space', 1), 'museum': ('museum', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
