"""Word-anchored beat times for web/lightning_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'one': ('one', 1), 'ranger': ('ranger', 1), 'hit1': ('hit', 1), 'lightning1': ('lightning', 1), 'seven1': ('seven', 1), 'times': ('times', 1),
    'every': ('every', 1), 'finds': ('finds', 1), 'somewhere': ('somewhere', 1), 'new': ('new', 1),
    's1': ('strike', 1), 'keeps': ('keeps', 1), 'hitting': ('hitting', 1), 'lookout': ('lookout', 1), 'tower': ('tower', 1), 'runs': ('runs', 1), 'outside': ('outside', 1),
    'then': ('then', 1), 'hits': ('hits', 1), 'toenail': ('toenail', 1),
    's2': ('strike', 2), 'comes': ('comes', 1), 'truck1': ('truck', 1), 'window': ('window', 1), 'burns': ('burns', 1), 'eyebrows': ('eyebrows', 1),
    's3': ('strike', 3), 'own': ('own', 1), 'front': ('front', 1), 'yard': ('yard', 1),
    's4': ('strike', 4), 'sets': ('sets', 1), 'hair1': ('hair', 1), 'fire1': ('fire', 1),
    'now': ('now', 1), 'carries': ('carries', 1), 'can': ('can', 1), 'water': ('water', 1),
    's5': ('strike', 5), 'spots': ('spots', 1), 'cloud': ('cloud', 1), 'races': ('races', 1),
    'steps': ('steps', 1), 'sure': ('sure', 1), 'safe': ('safe', 1),
    'hair2': ('hair', 2), 'fire2': ('fire', 2), 'again': ('again', 1),
    'soon': ('soon', 1), 'nobody': ('nobody', 1), 'stand': ('stand', 1), 'near': ('near', 1),
    'when': ('when', 1), 'lightning3': ('lightning', 3), 'flashes': ('flashes', 1), 'far': ('far', 1), 'boss': ('boss', 1), 'says': ('says', 1),
    'ill': ('ill', 1), 'later': ('later', 1),
    's6': ('strike', 6), 'gets': ('gets', 1), 'ankle': ('ankle', 1),
    's7': ('strike', 7), 'fishing': ('fishing', 1),
    'hair3': ('hair', 3), 'catches': ('catches', 1), 'bear': ('bear', 1), 'walks': ('walks', 1), 'steal': ('steal', 1), 'fish': ('fish', 1),
    'chases': ('chases', 1), 'still': ('still', 1), 'smoking': ('smoking', 1),
    'seven2': ('seven', 2), 'strikes': ('strikes', 1), 'survived': ('survived', 1), 'all': ('all', 1),
    'record': ('record', 1), 'stands': ('stands', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
