"""Word-anchored beat times for web/fairies_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'seventeen': ('seventeen', 1), 'girls': ('girls', 1), 'photo1': ('photo', 1), 'fairies1': ('fairies', 1),
    'later': ('later', 1), 'sherlock': ('sherlock', 1), 'world': ('world', 1), 'real1': ('real', 1),
    'elsie1': ('elsie', 1), 'cousin': ('cousin', 1), 'nine': ('nine', 1), 'wet': ('wet', 1), 'stream': ('stream', 1),
    'says1': ('says', 1), 'fairies2': ('fairies', 2),
    'borrows': ('borrows', 1), 'camera': ('camera', 1), 'shows': ('shows', 1), 'tiny': ('tiny', 1), 'dancing': ('dancing', 1),
    'dad': ('dad', 1), 'believe': ('believe', 1),
    'expert': ('expert', 1), 'trickery': ('trickery', 1), 'arthur': ('arthur', 1), 'doyle': ('doyle', 1), 'believes': ('believes', 1),
    'magazine': ('magazine', 1), 'book': ('book', 1), 'fairies3': ('fairies', 4),
    'sixty': ('sixty', 1), 'argue': ('argue', 1), 'eightythree': ('eightythree', 1), 'admit': ('admit', 1),
    'paper': ('paper', 1), 'cutouts': ('cutouts', 1), 'hatpins': ('hatpins', 1),
    'never': ('never', 1), 'photo3': ('photo', 4), 'until': ('until', 1), 'real2': ('real', 2),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    ALIAS = {'1917': 'seventeen', '16': 'sixteen', '9': 'nine', 'francis': 'frances', '60': 'sixty', '1983': 'eightythree', 'admitted': 'admit', 'pins': 'hatpins'}         # numerals Whisper writes for spoken words
    heard = [(ALIAS.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
