"""Word-anchored beat times for web/cup_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'pickles1': ('pickles', 1), 'drags': ('drags', 1), 'parcel': ('parcel', 1), 'hedge': ('hedge', 1),
    'inside': ('inside', 1), 'stolen1': ('stolen', 1), 'cup1': ('cup', 1),
    'week': ('week', 1), 'earlier': ('earlier', 1), 'show': ('show', 1), 'london': ('london', 1), 'four': ('four', 1),
    'england1': ('england', 1), 'tournament': ('tournament', 1),
    'guards': ('guards', 1), 'watch': ('watch', 1), 'night': ('night', 1),
    'sunday': ('sunday', 1), 'glass': ('glass', 1), 'empty': ('empty', 1),
    'ransom': ('ransom', 1), 'arrives': ('arrives', 1), 'fifteen': ('fifteen', 1), 'pounds': ('pounds', 1),
    'police1': ('police', 1), 'arrest': ('arrest', 1), 'handover': ('handover', 1),
    'says': ('says', 1), 'middleman': ('middleman', 1), 'trophy1': ('trophy', 1), 'missing': ('missing', 1),
    'pickles2': ('pickles', 2), 'walk': ('walk', 1), 'owner': ('owner', 1), 'fears': ('fears', 1), 'bomb': ('bomb', 1),
    'tears': ('tears', 1), 'paper': ('paper', 1), 'brazil1': ('brazil', 1), 'west': ('west', 1), 'uruguay': ('uruguay', 1),
    'takes': ('takes', 1), 'police2': ('police', 2), 'main': ('main', 1), 'suspect': ('suspect', 1),
    'question': ('question', 1), 'half': ('half', 1), 'morning': ('morning', 1),
    'summer': ('summer', 1), 'england2': ('england', 2), 'win': ('win', 1), 'cup2': ('cup', 2),
    'players': ('players', 1), 'invite': ('invite', 1), 'victory': ('victory', 1), 'dinner': ('dinner', 1),
    'licks': ('licks', 1), 'plates': ('plates', 1), 'clean': ('clean', 1),
    'seventeen': ('seventeen', 1), 'later': ('later', 1), 'stolen2': ('stolen', 2), 'again': ('again', 1), 'brazil2': ('brazil', 2),
    'time': ('time', 1), 'pickles4': ('pickles', 4), 'never': ('never', 1), 'found': ('found', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    ALIAS = {'15': 'fifteen', '000': 'pounds', '17': 'seventeen'}         # numerals Whisper writes for spoken words
    heard = [(ALIAS.get(norm(w['word']), norm(w['word'])), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
