"""Word-anchored beat times for web/cliff_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'five': ('five', 1), 'miles': ('miles', 1), 'sydney': ('sydney', 1), 'melbourne1': ('melbourne', 1),
    'runners1': ('runners', 1), 'shiny': ('shiny', 1), 'sixty': ('sixtyoneyearold', 1), 'potato': ('potato', 1), 'overalls': ('overalls', 1), 'boots': ('boots', 1),
    'nobody': ('nobody', 1), 'chance': ('chance', 1),
    'gun': ('gun', 1), 'sprint': ('sprint', 1), 'shuffles1': ('shuffles', 1), 'nightfall': ('nightfall', 1), 'behind': ('behind', 1),
    'night': ('night', 1), 'sleep1': ('sleep', 1), 'six': ('six', 1), 'wakes': ('wakes', 1), 'mistake': ('mistake', 1), 'two': ('two', 1), 'morning1': ('morning', 1),
    'starts': ('starts', 1), 'running': ('running', 1), 'shuffles2': ('shuffles', 2), 'tents': ('tents', 1), 'one': ('one', 1),
    'morning2': ('morning', 2), 'lead': ('lead', 1),
    'back': ('back', 1), 'sheep': ('sheep', 1), 'farm': ('farm', 1), 'days1': ('days', 1),
    'decides': ('decides', 1), 'sleep2': ('sleep', 2), 'all': ('all', 1),
    'faster1': ('faster', 1), 'stopping': ('stopping', 1), 'never': ('never', 1),
    'five2': ('five', 2), 'later': ('later', 1), 'shuffles3': ('shuffles', 3), 'melbourne2': ('melbourne', 2), 'ten1': ('ten', 1), 'hours': ('hours', 1), 'second': ('second', 1),
    'nearly': ('nearly', 1), 'record': ('record', 1),
    'hand': ('hand', 1), 'ten2': ('ten', 2), 'dollars': ('dollars', 1), 'gives': ('gives', 2), 'most': ('most', 1), 'beat': ('beat', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
