"""Word-anchored beat times for web/kitsune_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'giant': ('giant', 1), 'fell': ('fell', 1), 'sky': ('sky', 1), 'hunt': ('hunt', 1),
    'its': ('its', 1), 'kitsune': ('kitsune', 1), 'only': ('only', 1), 'eats': ('eats', 1),
    'dawn': ('dawn', 1), 'beasts': ('beasts', 1), 'sparkle': ('sparkle', 1), 'beam': ('beam', 1),
    'beat': ('beat', 1), 'drops': ('drops', 1),
    'leo': ('leo', 1), 'fed': ('fed', 1), 'one': ('one', 2), 'nom': ('nom', 1),
    'two': ('two', 1), 'three': ('three', 1), 'four': ('four', 1), 'nothing': ('nothing', 1),
    'five': ('five', 1), 'chest': ('chest', 1), 'inside': ('inside', 1), 'double': ('double', 1), 'fifteen': ('fifteen', 1),
    'but': ('but', 1), 'max': ('max', 1), 'prize': ('prize', 1), 'blade': ('blade', 1),
    'five2': ('five', 2), 'percent': ('percent', 1), 'so': ('so', 1), 'lot': ('lot', 1),
    'good': ('good', 1), 'thirty': ('thirty', 1), 'walk': ('walk', 1), 'passes': ('passes', 1), 'turns': ('turns', 1),
    'better': ('better', 1), 'hour': ('hour', 1), 'alpha': ('alpha', 1), 'lands': ('lands', 1),
    'whole': ('whole', 1), 'fights': ('fights', 1), 'then': ('then', 1), 'bursts': ('bursts', 1),
    'grabbed': ('grabbed', 1), 'two2': ('two', 2), 'mia': ('mia', 1), 'rest': ('rest', 1),
    'fed2': ('fed', 2), 'chest2': ('chest', 2), 'training': ('training', 1), 'again': ('again', 1), 'coins2': ('coins', 2),
    'opened': ('opened', 1), 'chest3': ('chest', 3), 'blade2': ('blade', 2),
    'hurry': ('hurry', 1), 'leaves': ('leaves', 1), 'friday': ('friday', 1),
    'play': ('play', 1), 'link': ('link', 1),
}
NUM = {'1': 'one', '2': 'two', '3': 'three', '4': 'four', '5': 'five', '15': 'fifteen', '30': 'thirty'}
def norm(w):
    w = re.sub(r"[^a-z0-9]", '', w.lower())
    return NUM.get(w, w)
def words(text):
    out = []
    for w in text.replace('-', ' ').replace('%', ' percent').split():
        if norm(w): out.append(norm(w))
    return out
script = [w for line in (P / 'script.txt').read_text().splitlines() for w in words(line)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(p, w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in words(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in words(line):
            heard.append((w, t, t + 0.3)); t += 0.34
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
