"""Word-anchored beat times for web/vampire_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'vampires': ('vampires', 1), 'sister1': ('sister', 1), 'single': ('single', 1), 'tempting1': ('tempting', 1), 'case1': ('case', 1),
    'brother': ('brother', 1), 'count': ('count', 1), 'vlad1': ('vlad', 1), 'nicest': ('nicest', 1), 'town': ('town', 1),
    'knocked': ('knocked', 1), 'cold': ('cold', 1), 'next': ('next', 1), 'coffin': ('coffin', 1), 'garlic1': ('garlic', 1),
    'bread1': ('bread', 1), 'somebody': ('somebody', 1), 'stop': ('stop', 1), 'chief': ('chief', 1), 'burger': ('burger', 1),
    'drop': ('drop', 1), 'tempting2': ('tempting', 2), 'case2': ('case', 2), 'sniffed': ('sniffed', 1), 'bread2': ('bread', 2),
    'longer': ('longer', 1), 'should': ('should', 1), 'extra': ('extra', 1), 'butter': ('butter', 1), 'fresh': ('fresh', 1),
    'garlic2': ('garlic', 2), 'hint': ('hint', 1), 'compost': ('compost', 1), 'garlic3': ('garlic', 3), 'homegrown': ('homegrown', 1),
    'only': ('only', 1), 'grows': ('grows', 1), 'gardener': ('gardener', 1), 'patch': ('patch', 1), 'roses': ('roses', 1),
    'vlad2': ('vlad', 2), 'kept': ('kept', 1), 'shade': ('shade', 1), 'twenty': ('twenty', 1), 'tomatoes': ('tomatoes', 1),
    'vlad3': ('vlad', 3), 'go': ('go', 1), 'cuffs': ('cuffs', 1), 'gloves': ('gloves', 1), 'gone': ('gone', 1), 'woke': ('woke', 1),
    'sister2': ('sister', 2), 'dinner': ('dinner', 1), 'fangs': ('fangs', 1), 'tempting3': ('tempting', 3), 'case3': ('case', 3),
    'follow': ('follow', 1),
}
NUM = {'1': 'one', '2': 'two', '20': 'twenty'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45 if line.strip() else 0.5
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
