"""Word-anchored beat times for web/clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'someone': ('someone', 1), 'stole': ('stole', 1), 'ten': ('ten', 1), 'again': ('again', 1), 'tonight': ('tonight', 1), 'hiding': ('hiding', 1),
    'bush': ('bush', 1), 'midnight': ('midnight', 1), 'footsteps': ('footsteps', 1), 'hooded': ('hooded', 1), 'thief': ('thief', 1),
    'sprints': ('sprints', 1), 'grabs': ('grabs', 1), 'every': ('every', 1), 'checked': ('checked', 1), 'fifty': ('fifty', 1),
    'thousand': ('thousand', 1), 'mine': ('mine', 1), 'nine': ('nine', 1), 'chased': ('chased', 1), 'second': ('second', 1), 'gone': ('gone', 1),
    'night2': ('two', 1), 'laser': ('laser', 1), 'limboed': ('limboed', 1), 'under': ('under', 1), 'night3': ('three', 1),
    'capybara': ('capybara', 1), 'bribed': ('bribed', 1), 'apple': ('apple', 1), 'stopped': ('stopped', 1), 'faster': ('faster', 1),
    'spent': ('spent', 1), 'mythic': ('mythic', 1), 'hatches': ('hatches', 1), 'sixty': ('sixty', 1), 'sign': ('sign', 1),
    'super': ('super', 1), 'steal': ('steal', 1), 'right': ('right', 1), 'thief2': ('thief', 2), 'grabbed': ('grabbed', 1), 'ran': ('ran', 1),
    'didnt': ('didnt', 1), 'counted': ('counted', 1), 'three': ('three', 2), 'two': ('two', 2), 'one': ('one', 4), 'hatched': ('hatched', 1),
    'giant': ('giant', 1), 'spinosaurus': ('spinosaurus', 1), 'pets': ('pets', 1), 'owner': ('owner', 1), 'picked': ('picked', 1),
    'hood': ('hood', 1), 'carried': ('carried', 1), 'me': ('me', 1), 'hoodoff': ('hood', 2), 'max': ('max', 1), 'best': ('best', 1),
    'said': ('said', 1), 'keeping': ('keeping', 1), 'safe': ('safe', 1), 'pays': ('pays', 1), 'treadmill': ('treadmill', 1),
    'fifty2': ('fifty', 2), 'paid': ('paid', 1), 'four': ('four', 1), 'seconds': ('seconds', 2), 'then': ('then', 1), 'broke': ('broke', 1),
    'treadmill2': ('treadmill', 2), 'follow': ('follow', 1),
}
NUM = {'3': 'three', '2': 'two', '1': 'one', '4': 'four', '10': 'ten', '60': 'sixty'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
