"""Word-anchored beat times for web/clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'sleeping': ('sleeping', 1), 'best': ('best', 1), 'tiptoed': ('tiptoed', 1), 'grabbed': ('grabbed', 1), 'woke': ('woke', 1),
    'problem': ('problem', 1), 'slow': ('slow', 1), 'bonk1': ('bonk', 1), 'flying1': ('flying', 1), 'laughed': ('laughed', 1),
    'tried': ('tried', 1), 'bonk2': ('bonk', 2), 'higher': ('higher', 1), 'three': ('three', 1), 'bush': ('bush', 1), 'ate': ('ate', 1),
    'bush2': ('bush', 2), 'seven': ('seven', 1), 'trap': ('trap', 1), 'stepped': ('stepped', 1), 'something': ('something', 1),
    'teamwork': ('teamwork', 1), 'waving': ('waving', 1), 'dancing': ('dancing', 1), 'anything': ('anything', 1), 'chased': ('chased', 1),
    'circles': ('circles', 1), 'grabbed2': ('grabbed', 2), 'waddled': ('waddled', 1), 'safe1': ('safe', 1), 'turned': ('turned', 1),
    'jumped': ('jumped', 1), 'tail': ('tail', 1), 'bonk3': ('bonk', 3), 'flying3': ('flying', 3), 'again': ('again', 1), 'made': ('made', 1),
    'safe2': ('safe', 2), 'follow1': ('follow', 1), 'hatched': ('hatched', 1), 'baby': ('baby', 1), 'dollar': ('dollar', 1), 'saw': ('saw', 1),
    'mias': ('mias', 1), 'twelve': ('twelve', 1), 'chased2': ('chased', 2), 'took': ('took', 1), 'rest': ('rest', 1), 'twelve2': ('twelve', 2),
    'hatched2': ('hatched', 2), 'cried': ('cried', 1), 'turns': ('turns', 1), 'guardians': ('guardians', 1), 'moms': ('moms', 1),
    'walked': ('walked', 1), 'took2': ('took', 2), 'babies': ('babies', 1), 'mia2': ('mia', 2), 'now': ('now', 1), 'sleeping2': ('sleeping', 2),
    'new': ('new', 2), 'follow': ('follow', 2),
}
NUM = {'3': 'three', '7': 'seven', '12': 'twelve', '1': 'one'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
