"""Word-anchored beat times for web/spaghetti_clip.js -> web/beats.js (export const W = {name: seconds}).

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'news': ('news', 1), 'family': ('family', 1), 'picking': ('picking', 1), 'off': ('off', 1), 'tree1': ('tree', 1),
    'eight': ('eight', 1), 'million': ('million', 1), 'watching': ('watching', 1),
    'its1': ('its', 1), 'britains': ('britains', 1), 'serious1': ('serious', 1), 'show1': ('show', 1),
    'in_sw': ('in', 1), 'switzerland': ('switzerland', 1), 'presenter': ('presenter', 1), 'mild': ('mild', 1), 'winter': ('winter', 1), 'bumper': ('bumper', 1), 'harvest': ('harvest', 1),
    'pickers': ('pickers', 1), 'lay': ('lay', 1), 'sun': ('sun', 1), 'dry': ('dry', 1),
    'dreaded': ('dreaded', 1), 'weevil': ('weevil', 1), 'almost': ('almost', 1), 'wiped': ('wiped', 1),
    'and1': ('and', 1), 'why': ('why', 1), 'same': ('same', 1), 'length': ('length', 1), 'years': ('years', 1), 'careful': ('careful', 1), 'breeding': ('breeding', 1),
    'back': ('back', 1), 'rare': ('rare', 1), 'britain2': ('britain', 1), 'most': ('most', 2), 'tin1': ('tin', 1),
    'so': ('so', 1), 'next': ('next', 1), 'hundreds': ('hundreds', 1), 'viewers': ('viewers', 1), 'phone': ('phone', 1),
    'is': ('is', 3), 'real': ('real', 1), 'how': ('how', 1), 'grow': ('grow', 1), 'tree2': ('tree', 2),
    'the_answer': ('answer', 1), 'place': ('place', 1), 'sprig': ('sprig', 1), 'tin2': ('tin', 2), 'tomato': ('tomato', 1), 'sauce': ('sauce', 1), 'hope': ('hope', 1), 'best': ('best', 1),
    'date': ('date', 1), 'show2': ('show', 2), 'april1': ('april', 1), 'first': ('first', 1),
    'it_was': ('was', 2), 'fools': ('fools', 1), 'joke': ('joke', 1),
    'and_its': ('and', 3), 'still': ('still', 1), 'biggest': ('biggest', 1), 'hoax': ('hoax', 1), 'pulled': ('pulled', 1),
    'follow': ('follow', 1),
}
norm = lambda w: re.sub(r"[^a-z0-9]", '', w.lower())
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(w['word']), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] if norm(w['word'])]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        if not line.strip(): t += 0.9; continue
        for w in line.split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.33 + (0.4 if '...' in w else 0)
        t += 0.4
    src = 'estimate'
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
