"""Word-anchored beat times -> web/beats.js (export const W = {name: seconds}) for web/clown_clip.js.

  python3 source/beats.py     # real narration (audio/alignment/captions.json) if present, else an estimate from script.txt

Anchors are (word, occurrence) in the SCRIPT. The script is aligned to the transcript with difflib, so a misheard word
elsewhere doesn't shift anything; an anchor whose own word was misheard takes the time of its nearest matched neighbours.
"""
import json, re, difflib
from pathlib import Path
P = Path(__file__).resolve().parent.parent
ANCHORS = {
    'girl': ('girl', 1), 'bar1': ('bar', 1), 'single': ('single', 1), 'tempting1': ('tempting', 1), 'case1': ('case', 1),
    'somebody': ('somebody', 1), 'kidnapped1': ('kidnapped', 1), 'wife1': ('wife', 1), 'election': ('election', 1),
    'chief': ('chief', 1), 'speech1': ('speech', 1), 'candidate': ('candidate', 1), 'clown1': ('clown', 1), 'figure': ('figure', 1),
    'ransom1': ('ransom', 1), 'ten': ('ten', 1), 'dollars': ('dollars', 1), 'sniffed': ('sniffed', 1), 'waffle': ('waffle', 1),
    'fudge': ('fudge', 1), 'hint': ('hint', 1), 'mint': ('mint', 1), 'only': ('only', 1), 'smells': ('smells', 1),
    'big1': ('big', 1), 'scoops': ('scoops', 1), 'suspicious': ('suspicious', 1), 'owner': ('owner', 1), 'free1': ('free', 1),
    'sundae1': ('sundae', 1), 'tempting2': ('tempting', 2), 'case2': ('case', 2), 'out': ('out', 1), 'wife2': ('wife', 2),
    'tied': ('tied', 1), 'till': ('till', 1), 'faked': ('faked', 1), 'ransom2': ('ransom', 2), 'truck': ('truck', 1),
    'crew': ('crew', 1), 'objected': ('objected', 1), 'flying': ('flying', 1), 'sundae2': ('sundae', 2), 'later': ('later', 1),
    'anyway': ('anyway', 1), 'gave': ('gave', 1), 'speech2': ('speech', 2), 'smile': ('smile', 1), 'clown2': ('clown', 2),
    'won': ('won', 1), 'black': ('black', 1), 'eye': ('eye', 1), 'free2': ('free', 2), 'sundae3': ('sundae', 3),
    'tempting3': ('tempting', 3), 'follow': ('follow', 1),
}
NUM = {'1': 'one', '2': 'two', '10000': 'ten'}
norm = lambda w: NUM.get(re.sub(r"[^a-z0-9]", '', w.lower()), re.sub(r"[^a-z0-9]", '', w.lower()))
script = [norm(w) for line in (P / 'script.txt').read_text().splitlines() for w in line.replace('-', ' ').split() if norm(w)]
cap = P / 'audio/alignment/captions.json'
if cap.is_file():
    heard = [(norm(p), w['start'], w['end']) for seg in json.loads(cap.read_text()) for w in seg['words'] for p in w['word'].replace('-', ' ').split() if norm(p)]
    src = 'narration'
else:
    heard, t = [], 0.0
    for line in (P / 'script.txt').read_text().splitlines():
        for w in line.replace('-', ' ').split():
            if norm(w): heard.append((norm(w), t, t + 0.3)); t += 0.36 + (0.4 if '...' in w else 0)
        t += 0.45 if line.strip() else 0.5
    src = 'estimate'
# script index -> time, via alignment
when = {}
for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, script, [h[0] for h in heard], autojunk=False).get_opcodes():
    if tag == 'equal':
        for k in range(i2 - i1): when[i1 + k] = heard[j1 + k][1]
idx = sorted(when)
def at(i):
    if i in when: return when[i]
    lo = max([k for k in idx if k < i], default=None); hi = min([k for k in idx if k > i], default=None)
    if lo is None: return when[hi]
    if hi is None: return when[lo]
    return when[lo] + (when[hi] - when[lo]) * (i - lo) / (hi - lo)
W = {}
for name, (word, occ) in ANCHORS.items():
    hits = [i for i, w in enumerate(script) if w == word]
    if len(hits) < occ: raise SystemExit(f'anchor {name}: "{word}" #{occ} not in script.txt')
    W[name] = round(at(hits[occ - 1]), 2)
W['end'] = round(heard[-1][2], 2)
missed = [n for n, (word, occ) in ANCHORS.items() if [i for i, w in enumerate(script) if w == word][occ - 1] not in when]
(P / 'web/beats.js').write_text(f'// Generated by source/beats.py from the {src} - do not edit by hand.\nexport const W = {json.dumps(W, indent=1)};\n')
print(src, 'speech ends', W['end'], '|', len(W), 'anchors', ('| interpolated: ' + ', '.join(missed)) if missed else '')
